<a href="https://colab.research.google.com/github/vinicuervo/Calculo-Numerico/blob/main/Atividade_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Vinicius Cruz Cuervo - Integral**

In [1]:
import numpy as np


def eliminacao_gauss(A, b):
  # Converter para array do NumPy com ponto flutuante (evita divisão inteira)
  A = np.array(A, dtype=float)
  b = np.array(b, dtype=float).reshape(-1, 1)
  n = len(b)

  # 1. Formar a matriz aumentada [A | b]
  Ab = np.hstack([A, b])
  print("Matriz Aumentada Inicial [A | b]:")
  print(Ab)
  print("-" * 50)

  # 2. Eliminar os elementos abaixo dos pivôs (Triangularização)
  for k in range(n - 1):
    pivo = Ab[k, k]

    if pivo == 0:
      raise ValueError(
          f"Pivô nulo encontrado na posição ({k},{k}). O método sem pivoteamento"
          " falhou."
      )

    for i in range(k + 1, n):
      m = Ab[i, k] / pivo  # Multiplicador
      Ab[i, k:] = Ab[i, k:] - m * Ab[k, k:]

  print("Matriz Aumentada Triangularizada Superior:")
  print(Ab)
  print("-" * 50)

  # 3. Aplicar substituição regressiva
  x = np.zeros(n)
  for i in range(n - 1, -1, -1):
    soma = np.sum(Ab[i, i + 1 : n] * x[i + 1 : n])
    x[i] = (Ab[i, n] - soma) / Ab[i, i]

  # 4. Exibir a solução calculada
  print("Solução calculada (Eliminação de Gauss):")
  for i in range(n):
    print(f"  x[{i+1}] = {x[i]:.4f}")
  print("-" * 50)

  return x


# ==============================================================================
# Teste com o sistema do Exercício 2:
# 2x +  y -  z =   8
# -3x -  y + 2z = -11
# -2x +  y + 2z =  -3
# ==============================================================================

A_ex2 = np.array([[2, 1, -1], [-3, -1, 2], [-2, 1, 2]])

b_ex2 = np.array([8, -11, -3])

# Execução do algoritmo próprio
x_gauss = eliminacao_gauss(A_ex2, b_ex2)

# Comparação com o numpy.linalg.solve
x_numpy = np.linalg.solve(A_ex2, b_ex2)

print("Comparação dos Resultados:")
print(f"  Eliminação de Gauss : {x_gauss}")
print(f"  numpy.linalg.solve  : {x_numpy}")
print(f"  Diferença Absoluta Máxima: {np.max(np.abs(x_gauss - x_numpy)):.2e}")

Matriz Aumentada Inicial [A | b]:
[[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]
--------------------------------------------------
Matriz Aumentada Triangularizada Superior:
[[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   0.  -1.   1. ]]
--------------------------------------------------
Solução calculada (Eliminação de Gauss):
  x[1] = 2.0000
  x[2] = 3.0000
  x[3] = -1.0000
--------------------------------------------------
Comparação dos Resultados:
  Eliminação de Gauss : [ 2.  3. -1.]
  numpy.linalg.solve  : [ 2.  3. -1.]
  Diferença Absoluta Máxima: 5.55e-16


# **Exercício 5) b**

In [4]:
# ==============================================================================
# Exercício 5:
# 4 T1 - T2  =  15
# -T1 + 4 T2 - T3 = 10
# -T2 + 3 T3 =  10
# ==============================================================================

A_ex5 = np.array([[4, -1, 0], [-1, 4, -1], [0, -1, 3]])

b_ex5 = np.array([15, 10, 10])

# Execução do algoritmo próprio
x_gauss = eliminacao_gauss(A_ex5, b_ex5)

# Comparação com o numpy.linalg.solve
x_numpy = np.linalg.solve(A_ex5, b_ex5)

Matriz Aumentada Inicial [A | b]:
[[ 4. -1.  0. 15.]
 [-1.  4. -1. 10.]
 [ 0. -1.  3. 10.]]
--------------------------------------------------
Matriz Aumentada Triangularizada Superior:
[[ 4.         -1.          0.         15.        ]
 [ 0.          3.75       -1.         13.75      ]
 [ 0.          0.          2.73333333 13.66666667]]
--------------------------------------------------
Solução calculada (Eliminação de Gauss):
  x[1] = 5.0000
  x[2] = 5.0000
  x[3] = 5.0000
--------------------------------------------------
